### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by herbiezhao** [vacancy/PyPatchMatch#1]
when i run "python py_example.py", I got the error"libgio-2.0.so.0: undefined symbol: g_ref_count_inc", I don't know how to fix it

my system is ubuntu1804

**Comment by vacancy** [comment]
Sorry haven't encountered similar issues before. I suspect this is an issue with your system package installation. There might be a version confliction between opencv and your glib.

Can you make sure that your opencv is properly installed? For example, can you successfully compile and run the following c++?

```
#include <opencv2/imgcodecs.hpp>
#include <opencv2/highgui.hpp>

int main() {
    auto source = cv::imread("./images/forest_pruned.bmp", cv::IMREAD_COLOR);
    auto result = source;
    cv::imwrite("./images/forest_recovered.bmp", result);
    return 0;
}
```

**Comment by herbiezhao** [comment]
I had fixed it using python3.6 instead of python 3.7
