### ISSUE TITLE
General Questions about the Inpainting algorithm

### ISSUE THREAD

**Issue by mightimatti** [vacancy/PyPatchMatch#10]
Hi,
first of all thank you for this excellent implementation of PatchMatch-based inpainting. 
I am currently using this repository in a project at University. As I had good results using this method,  I am now in the process of modifying it to gain speed through the use of CUDA.

After having spent more time than I am proud to admit perusing this code to gain a basic understanding of how it works and comparing it to other implementations of PM found online, I spent even more time modifying the build system to incorportate(and properly link CUDA dependencies). While all of that works now, I have  encountered a couple of questions while debugging my code, some of which I can't seem to clarify.

Is there a publication or text outlining the method behind how inpainting is performed? I have a solid understanding of how PatchMatch and it's NNF works, I don't really understand why the "Expectation Maximization" side of things is implemented the way it is and some aspects seem very arbitrary... Comments, as far as I can tell copied from @younesse-cv code, reference specific pages of a paper, but I don' think they are referring to the original PatchMatch publication.  Is there a text I could read to gain a high-level understanding of the method?

What exactly is the role of the so-called Global mask? 

Thank you very much, 

mattia Stellacci

**Comment by vacancy** [comment]
Hi Mattia

Thank you for your interest! I think the best reference would be the original SIGGRAPH paper https://gfx.cs.princeton.edu/pubs/Barnes_2009_PAR/patchmatch.pdf

This is a classical algorithm so there might be other slides/videos online.

Re EM: I think this is just a way to interpret the iterative algorithm that iteratively find the most similar patches and then inpaint the missing pixels.

Re global_mask: this is a feature I added for convenience. Typically when doing PatchMatch you are supposed to find similar patches across the entire image. By adding the global_mask, the algorithm will now only find similar patches inside the global_mask

Hope this helps

**Comment by mightimatti** [comment]
Thank you for the swift response.

I must have somehow missed the section in that publication, maybe I was looking at a different version...
The decisive clue I needed was actually the reference to "Summarizing Visual Data Using Bidirectional Similarity" by Simakov et al. I had a hunch there would be some prior publication that described the iterative refinement in more depth. It just seemed too involved and worthy of some elaboration!  

In any case I feel like I have everything I need now to complete my CUDA implementation. 
Thanks again!
