### ISSUE TITLE
about distance metric

### ISSUE THREAD

**Issue by herbiezhao** [vacancy/PyPatchMatch#2]
Could you give me some information about RegularityGuidedPatchDistanceMetricV1 and RegularityGuidedPatchDistanceMetricV2?
And how to use these two metric?

**Comment by vacancy** [comment]
They are unpublished work and details will be released in the future. The standard PatchMatch algorithm uses PatchSSDDistanceMetric.

**Comment by herbiezhao** [comment]
ok，thanks
