### ISSUE TITLE
Library Not Loaded error for c++

### ISSUE THREAD

**Issue by IamRo45** [vacancy/PyPatchMatch#5]
I have built the library using make 
and trying to run c++ examples by running the bash file cpp_example_run.sh. But getting this error. I am on MacOs.

dyld: Library not loaded: libpatchmatch.so
  Referenced from: /Users/rohit.kumar/mywork/PyPatchMatch/examples/./cpp_example.exe
  Reason: image not found
Command terminated abnormally.

**Comment by vacancy** [comment]
Try LD_LIBRARY_PATH => DYLD_LIBRARY_PATH in cpp_example_run.sh

**Comment by IamRo45** [comment]
I tried that one but not working. I ran it inside a docker container with ubuntu image, there it's running. Is it due to the fact that MakeFile will be different for MacOs?

**Comment by vacancy** [comment]
No. It works for me on macOS Big Sur

```
$ xcodebuild -version

Xcode 12.5.1
Build version 12E507

$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by vacancy** [comment]
Oh I see. Remove "time" at L14. Just run the exe directly.
DYLD does not propagate.

**Comment by vacancy** [comment]
Can you try the latest version on master branch? I just pushed a modification to the shell file.

**Comment by IamRo45** [comment]
Thanks it is working now.
